---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: postgres-operator
      version: "1.12.2"
      sourceRef:
        kind: HelmRepository
        name: postgres-operator
      interval: 12h
