---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: "4.0.1"
      sourceRef:
        kind: HelmRepository
        name: openebs
      interval: 12h
  values:
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
    ndm:
      enabled: false
    hostpathClass:
      reclaimPolicy: Delete
      isDefaultClass: true
