---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx-external
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: maxime-in-flux-sync
  path: infrastructure/controllers/ingress-nginx-external
  dependsOn:
    - name: metallb
    - name: l2-aware-lb
