apiVersion: v1
kind: ServiceAccount
metadata:
  name: home-assistant-store
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: home-assistant-store-role
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectrulesreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: home-assistant-store-role-binding
  namespace: home-assistant
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: home-assistant-store-role
subjects:
  - kind: ServiceAccount
    name: home-assistant-store
    namespace: home-assistant
