apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: home-assistant-store
  target:
    name: home-assistant-secrets
    template:
      engineVersion: v2
      templateFrom:
        - target: Data
          configMap:
            name: home-assistant-configuration
            items:
              - key: secrets.yaml
                templateAs: Values
              - key: linky.json
                templateAs: Values
  data:
    - secretKey: postgresUser
      remoteRef:
        key: ha.postgres.credentials.postgresql.acid.zalan.do
        property: username
    - secretKey: postgresPassword
      remoteRef:
        key: ha.postgres.credentials.postgresql.acid.zalan.do
        property: password
    - secretKey: linkyPrm
      remoteRef:
        key: linky-credentials
        property: prm
    - secretKey: linkyToken
      remoteRef:
        key: linky-credentials
        property: token
