apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: home-assistant-store
spec:
  provider:
    kubernetes:
      remoteNamespace: home-assistant
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: home-assistant-store
