---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: maxime-in-ca
spec:
  isCA: true
  duration: 8760h # 1 year
  renewBefore: 360h # 15 days
  commonName: maxime-in-ca
  secretName: maxime-in-ca
  issuerRef:
    name: maxime-in-selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
