---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: maxime-in-selfsigned-cluster-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: maxime-in-cluster-issuer
spec:
  ca:
    secretName: maxime-in-ca
