apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system

resources:
  - apps/minecraft.yaml
  - apps/pihole.yaml
  - infrastructure/configurations/external-names.yaml
  - infrastructure/configurations/l2-aware-lb.yaml
  - infrastructure/configurations/self-signed-ca.yaml
  - infrastructure/configurations/storage-classes.yaml
  - infrastructure/controllers/cert-manager.yaml
  - infrastructure/controllers/external-dns.yaml
  - infrastructure/controllers/ingress-nginx.yaml
  - infrastructure/controllers/metallb.yaml
  - infrastructure/controllers/openebs.yaml
  - infrastructure/controllers/weave-gitops.yaml
  - infrastructure/crds/gateway-api.yaml
