kind: Service
apiVersion: v1
metadata:
  name: mabbox
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mabbox.bytel.fr
spec:
  type: ExternalName
  externalName: 192.168.1.1
---
kind: Service
apiVersion: v1
metadata:
  name: rocky
  annotations:
    external-dns.alpha.kubernetes.io/hostname: rocky,rocky.compute.maxime.in
spec:
  type: ExternalName
  externalName: 10.42.0.10
---
kind: Service
apiVersion: v1
metadata:
  name: cluster
  annotations:
    external-dns.alpha.kubernetes.io/hostname: cluster.k8s.maxime.in
spec:
  type: ExternalName
  externalName: 10.42.0.10
