apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: maxime-in-letsencrypt-cluster-issuer
spec:
  acme:
    email: webmaster@maxime.in
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: maxime-in-letsencrypt-cluster-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: nginx-external
