apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-storage
spec:
  storageClassName: local-hostpath-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-blueprints
spec:
  storageClassName: local-hostpath-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
