---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
spec:
  interval: 30m
  chart:
    spec:
      chart: pihole
      version: "2.24.0"
      sourceRef:
        kind: HelmRepository
        name: pihole
      interval: 12h
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: maxime-in-cluster-issuer
      hosts:
        - pihole.maxime.in
      tls:
        - hosts:
            - pihole.maxime.in
          secretName: pihole.maxime.in
    virtualHost: pihole.maxime.in
    serviceDns:
      mixedService: true
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: dns.maxime.in
      extraLabels:
        maxime.in/service: pihole
    serviceWeb:
      https:
        enabled: false
    doh:
      enabled: true
      envVars:
        { DOH_UPSTREAM: "https://1.1.1.1/dns-query,https://1.0.0.1/dns-query" }
    persistentVolumeClaim:
      enabled: true
      storageClass: openebs-hostpath
