---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: maxime-in-ip-pool
spec:
  addresses:
    - 10.42.0.150/31
    - 10.42.0.152/29
    - 10.42.0.160/27
    - 10.42.0.192/29
    - 10.42.0.200/32
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pihole-ip-pool
spec:
  serviceAllocation:
    serviceSelectors:
      - matchLabels:
          maxime.in/service: pihole
  addresses:
    - 10.42.0.253/32
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: minecraft-ip-pool
spec:
  serviceAllocation:
    serviceSelectors:
      - matchLabels:
          maxime.in/service: minecraft
  addresses:
    - 10.42.0.252/32
