---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: maxime-in-ip-pool
spec:
  addresses:
    - 10.42.100.0/24
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pihole-ip-pool
spec:
  serviceAllocation:
    serviceSelectors:
      - matchLabels:
          maxime.in/service: pihole
  addresses:
    - 10.42.255.253/32
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: minecraft-ip-pool
spec:
  serviceAllocation:
    serviceSelectors:
      - matchLabels:
          maxime.in/service: minecraft
  addresses:
    - 10.42.110.1/32
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: nginx-ingress-external-ip-pool
spec:
  serviceAllocation:
    serviceSelectors:
      - matchLabels:
          maxime.in/service: nginx-ingress-external
  addresses:
    - 10.42.255.252/32
