---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
spec:
  interval: 30m
  chart:
    spec:
      chart: minecraft
      version: "4.19.0"
      sourceRef:
        kind: HelmRepository
        name: itzg
      interval: 12h
  values:
    minecraftServer:
      eula: true
      version: "1.21"
      type: FABRIC
      difficulty: normal
      levelSeed: "1584853961"
      ops: iverly
      spawnProtection: 0
      memory: 8G
      viewDistance: 16
      serviceType: NodePort
    serviceLabels:
      area-51.fr/service: minecraft
    serviceAnnotations:
      external-dns.alpha.kubernetes.io/hostname: minecraft.area-51.fr
    persistence:
      dataDir:
        enabled: true
        Size: 30Gi
    resources:
      requests:
        cpu: 2
        memory: 4Gi
