---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-names
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: maxime-in-flux-sync
  path: infrastructure/configurations/external-names
  dependsOn:
    - name: pihole
    - name: external-dns
