---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: self-signed-ca
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: maxime-in-flux-sync
  path: infrastructure/configurations/self-signed-ca
  dependsOn:
    - name: cert-manager
